version: "4.0"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: materi-golang-api
    container_name: materi-golang-api
    networks:
        - materigolang
    ports:
        - 4010:4002
    volumes:
        - .env:/usr/app/.env
networks:
  sidig:
    driver: bridge
    